### ISSUE TITLE
Engine does not work with Apache Spark 2.1.0

### ISSUE THREAD

**Issue by bzz** [src-d/engine#189]
It would be nice to support 2.x version of Apache Spark, but if not feasible - have minimum working version documented.

Right now, if one tries Engine with Apache Spark 2.1.0 he will get

```
ava.lang.NoSuchMethodError: org.apache.spark.sql.UDFRegistration.register(Ljava/lang/String;Lorg/apache/spark/sql/expressions/UserDefinedFunction;)Lorg/apache/spark/sql/expressions/UserDefinedFunction;
  at tech.sourced.engine.package$SessionFunctions$$anonfun$registerUDFs$1.apply(package.scala:62)
  at tech.sourced.engine.package$SessionFunctions$$anonfun$registerUDFs$1.apply(package.scala:62)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at tech.sourced.engine.package$SessionFunctions.registerUDFs(package.scala:62)
  at tech.sourced.engine.Engine.<init>(Engine.scala:40)
  at tech.sourced.engine.Engine$.apply(Engine.scala:185)
  ... 50 elided
```

Apache Spark 2.2 works as expected

**Comment by erizocosmico** [comment]
Added to the docs.

**Comment by leanne0925** [comment]
But, may I ask how to solve this issue?
